[project]
name = "lsst-cmservice-web"
dynamic = ["version"]
description = "CM Service Web App"
requires-python = ">=3.12,<3.14"
dependencies = [
    "deepdiff>=8.6.1",
    "networkx>=3.5",
    "nicegui>=3.7.0",
    "pydantic>=2.12",
    "pydantic-extra-types>=2.10.5",
    "pydantic-settings>=2.12",
    "structlog>=24.4.0",
    "lsst-cm-service",
]

[project.scripts]
web = "lsst.cmservice.web.libexec:go"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
ignore-vcs = true

[tool.hatch.build.targets.wheel]
ignore-vcs = true
packages = ["src/lsst"]

[tool.hatch.version]
path = "src/lsst/cmservice/web/__init__.py"
